### ISSUE TITLE
docker update - : ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by vukomir** [bitnami/bitnami-docker-dokuwiki#42] opened 2018-04-02 19:50 UTC
**Description**

nami    INFO  Initializing dokuwiki
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, chown '/bitnami/dokuwiki/lib/images/smileys/local'

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
Send us your feedback at containers@bitnami.com

**Steps to reproduce the issue:**

1. [First Step]
updated image to last version
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
# docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:40 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:13 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.12.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 97
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63GiB
Name: pintcfg01
ID: NZ2C:HYZY:P7XG:ONPE:JVJH:AHLZ:DRA7:WXZO:N265:K5KM:QZ7P:CJAU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
s# docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:40 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
root@pintcfg01:~/docker/tools# docker-compose version
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
physical

**Comment by juan131** [comment] 2018-04-04 10:04
Hi @vukomir 

I was unable to reproduce the issue. Was it a "clean initialisation"? I mean, did you add any volume to the container that had been previously used on other containers?

I did not find any issue running the commands:

```
docker-compose down -v --rmi all
docker-compose up
```

**Comment by vukomir** [comment] 2018-04-05 19:53
Hi, 

it was a clean initialization, did not do any volume changes.

deleting all images did not help :(

**Comment by juan131** [comment] 2018-04-06 08:10
Hi @vukomir could you please share the command you used to create the container? Are you using the default `docker-compose.yaml` or did you create it using any specific command? 

Please provide as much information as possible so we can reproduce the issue.

**Comment by juan131** [comment] 2018-04-09 10:55
Hi @kyz3 

We added the directory **/opt/bitnami/dokuwiki/lib/images/smileys/local** to the list of persisted directories on release **"0.20170219.201708232029-r5"** (commit https://github.com/bitnami/bitnami-docker-dokuwiki/commit/8aa19d3a4c98910edef169086354d6d372d12f3c)

When upgrading from previous versions, it's necessary to create this directory on the persisted directory. 

Could you try with the following workaround?

 * Create the container with the old version of Dokuwiki (attaching the same volume as you did before)
 * Create the directory **lib/images/smileys/local** on the persisting directory.

```
docker exec <CONTAINER_ID> mkdir -p /bitnami/dokuwiki/lib/images/smileys/local
```

 * Copy the content of **/opt/bitnami/dokuwiki/lib/images/smileys/local** to that directory

```
docker exec <CONTAINER_ID> cp -rf /opt/bitnami/dokuwiki/lib/images/smileys/local/* /bitnami/dokuwiki/lib/images/smileys/local
```

 * Upgrade your container to latest version as you did before.

**Comment by kyz3** [comment] 2018-04-09 18:41
Hi @juan131, thank you for your reply.
I have started a new instance with the release you posted, however it did not really work any different than before.
I removed the local folder altogether, and it seems a link gets created at the initialization script:

`Error executing 'postInstallation': Path '/bitnami/dokuwiki/lib/images/smileys/local' does not exists`
`nami    INFO  Initializing dokuwiki`
`Error executing 'postInstallation': ELOOP: too many symbolic links encountered, chown '/bitnami/dokuwiki/lib/images/smileys/local'`

I did try this with older builds, up to about a month old (i think it was 0.20170219.201708232029-r4) and all behave the same way.

**Comment by juan131** [comment] 2018-04-10 08:44
Hi @kyz3 

Could you run the container setting the env. variable  **NAMI_DEBUG** to  **"--log-level trace"** and share the output?

**Comment by jolentes** [comment] 2018-04-13 06:41
I ran into the same issue today when upgrading dokuwik to the latest image.
I was running 0.20170219.201708232029-r2 and updated to 0.20170219.201708232029-r6.

I tried to revert back but it gave the same error. I have /bitnami mounted as volume to persist data.
In <volume-mount-point>/dokuwiki/lib/images/smileys there was a symbolic link to /bitnami/dokuwiki/lib/images/smileys/local. Which in the docker container results in a self reference.

- I removed the link.
- Created the directory in the container `mkdir -p /bitnami/dokuwiki/lib/images/smileys/local`
- Change to `cd /opt/bitnami/dokuwiki/lib/images/smileys/local/`

But the directory does not exist.

**Comment by juan131** [comment] 2018-04-13 10:44
Hi @jolentes 

I was able to reproduce the issue by launching a container with image **0.20170219.201708232029-r2** and then update to **0.20170219.201708232029-r6.**

See the error obtained using **"--log-level trace"**:

```
dokuwik TRACE [configurePermissions] File to chown: /bitnami/dokuwiki/lib/images/smileys/local
dokuwiki_1  | dokuwik TRACE [retry] Trying to configure permissions... 0 remaining attempts
dokuwiki_1  | Error executing 'postInstallation': Path '/bitnami/dokuwiki/lib/images/smileys/local' does not exists
dokuwiki_1  | nami    TRACE Error: Error executing 'postInstallation': Path '/bitnami/dokuwiki/lib/images/smileys/local' does not exists
```

I fixed it with the workaround below:

Launch container with image **0.20170219.201708232029-r2** and create missing directory:

```
docker-compose up
docker-compose exec dokuwiki mkdir -p /bitnami/dokuwiki/lib/images/smileys/local
```

Update to **0.20170219.201708232029-r6**:

```
sed -i -e 's/dokuwiki:0.20170219.201708232029-r2/dokuwiki:0.20170219.201708232029-r6/g' docker-compose.yml
docker-compose down
docker-compose up
```

Could you please try it?

**Comment by jolentes** [comment] 2018-04-16 07:35
Hi @juan131,

glad you could replicate it.
I tested it and these steps are working. But remember that are my first try there was a sym-link created in that place of the directory which I deleted. That might be a step that you need to add.

I a post before you asked to copy files from that folder. What did you expect to be in there?
How can I check if something is missing?

**Comment by juan131** [comment] 2018-04-16 11:44
> In a post before you asked to copy files from that folder. What did you expect to be in there? How can I check if something is missing?

You can omit this step if you did not create any custom emoji. However, if you created you own emojis, you should copy all the data within the  **lib/images/smileys/local** to the persisted volume. 

If you want to know more about the reasons why we wanted to persist this directory, see https://github.com/bitnami/bitnami-docker-dokuwiki/issues/40

**Comment by jolentes** [comment] 2018-04-17 06:45
For me it is fine.
Thank you very much for your support !!!

**Comment by juan131** [comment] 2018-04-17 07:55
That's great! I'll keep the issue opened since it's necessary the workaround suggested in order to upgrade from **0.20170219.201708232029-r2** on. I'll close it once we update the README.md file documenting this issue.

**Comment by juan131** [comment] 2018-04-17 09:28
I updated the README.md 

Please see [#Notable changes](https://github.com/bitnami/bitnami-docker-dokuwiki#notable-changes) to find information about this workaround. 

I proceed to close this issue. Please do not hesitate to open it again if you need further help.

**Closed by juan131** 2018-04-17 09:28 UTC
