### ISSUE TITLE
cant login when using traefik?

### ISSUE THREAD

**Issue by thepenguinthatwants** [bitnami/bitnami-docker-dokuwiki#60] opened 2019-06-23 18:25 UTC
Hi!

I tried this on traefik docker-compose and there is no login possibilities. Any ways to debug? docker-compose logs didn't show any errors

```
version: '3'
services:


  dokuwiki:
    image: bitnami/dokuwiki:latest
    restart: always
    volumes:
    - '/home/someone/dokuwiki:/bitnami'
    networks:
      - web
    ports:
      - "8081:80"
    environment:
      - DOKUWIKI_USERNAME=man
      - DOKUWIKI_PASSWORD=man
      - DOKUWIKI_WIKI_NAME=man
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:dokuwiki.example.xyz"

networks:
  web:
    external: true

```

**Comment by thepenguinthatwants** [comment] 2019-06-23 18:33
Okay there was something wrong with the volume ..deleting it and applying again worked.

**Comment by carrodher** [comment] 2019-06-24 06:59
Thanks for letting us know, I will close the issue; but, please, feel free to reopen it if the issue is still present.

**Closed by carrodher** 2019-06-24 06:59 UTC
