### ISSUE TITLE
Plugin & Template directory is not writable

### ISSUE THREAD

**Issue by imRichardNg** [bitnami/bitnami-docker-dokuwiki#28] opened 2017-05-10 04:13 UTC
## Issue

- Plugin directory is not writable
- Template directory is not writable

### Details

- It looks like `lib` and `tpl` folder already has the right permission.
- However, the folder belongs to the `root` while apache runs on `daemon`.

Could this be the issue?

#### Container details

```
root@f21031daf4ae:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4224   652 ?        Ss   04:03   0:00 tini -- nami start --foreground apache
root        83  0.0  1.6 387148 33648 ?        Ss   04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      84  0.0  1.7 392556 35084 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      85  0.1  1.5 390464 31376 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      86  0.2  1.6 390872 33928 ?        S    04:03   0:01 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      87  0.0  1.4 388956 29304 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      88  0.1  1.3 389136 28616 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      91  0.0  1.6 392220 33420 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      92  0.2  1.6 392292 34700 ?        S    04:03   0:01 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      93  0.0  1.2 387652 25072 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon      94  0.0  1.4 390412 30492 ?        S    04:03   0:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
root        95  0.4  2.4 956640 49696 ?        Sl   04:03   0:01 /opt/bitnami/nami/runtime/node --max_semi_space_size=150 /opt/bitnami/nami/ind
root       114  4.0  0.1  20248  3248 ?        Ss   04:10   0:00 /bin/bash
root       119  0.0  0.1  17500  2076 ?        R+   04:10   0:00 ps aux

root@f21031daf4ae:/opt/bitnami/dokuwiki/lib# ls -ltrh
total 28K
-rw-rw-r--  1 root root  241 May  4 07:54 index.html
drwxrwxr-x  8 root root 4.0K May  4 08:09 images
drwxrwxr-x  2 root root 4.0K May  4 08:09 exe
drwxrwxr-x 18 root root 4.0K May  4 08:09 plugins
drwxrwxr-x  3 root root 4.0K May  4 08:09 tpl
drwxrwxr-x  2 root root 4.0K May  4 08:09 styles
drwxrwxr-x  3 root root 4.0K May  4 08:09 scripts
```

#### `docker-compose.yml` details

```
version: '2'

services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    ports:
      - '880:80'
      - '8443:443'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'

volumes:
  dokuwiki_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```

## Docker details

- Host OS and version: 

    `macOS Sierra, v10.12.4`

- Docker version ($ docker version)

```    
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of $ docker info

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: NFQP:NCET:H74G:P63O:RBSK:LGAS:FVUQ:GELW:CJ7I:WX7X:6QUM:A4OH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 34
 System Time: 2017-05-10T04:07:50.741467632Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Version of this container ($ echo $BITNAMI_APP_VERSION inside the container)

```
$ env
...
BITNAMI_IMAGE_VERSION=2017.02.19-r0
```

- The command you used to run the container, and any relevant output you saw (masking any sensitive
information)

```
RICHARDs-Air:dokuwiki richard$ docker-compose up -d --build
RICHARDs-Air:dokuwiki richard$ docker logs -f dokuwiki_dokuwiki_1 

Welcome to the Bitnami dokuwiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-dokuwiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-dokuwiki/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing dokuwiki
dokuwik INFO  Passing wizard, please be patient
dokuwik INFO 
dokuwik INFO  ########################################################################
dokuwik INFO   Installation parameters for dokuwiki:
dokuwik INFO     username: superuser
dokuwik INFO     user fullname: Full Name
dokuwik INFO     Password: **********
dokuwik INFO     Email: user@example.com
dokuwik INFO     Wiki Name: Bitnami DokuWiki
dokuwik INFO   (Passwords are not shown for security reasons)
dokuwik INFO  ########################################################################
dokuwik INFO 
nami    INFO  dokuwiki successfully initialized
INFO  ==> Starting dokuwiki... 
172.18.0.1 - - [10/May/2017:04:03:22 +0000] "GET /doku.php?id=start HTTP/1.1" 200 2556
```

**Comment by dbarranco** [comment] 2017-05-10 11:27
Hi @imRichardNg 

Thank you so much for reporting this. 
I've been able to reproduce the issue and we will change those permissions in the next revision of the module.

Could you check if executing

`sudo chown -R root:daemon /opt/bitnami/dokuwiki/lib/`

fixes the issue? After executing that I did not find any issue.

Best regards!

**Comment by imRichardNg** [comment] 2017-05-10 12:09
Hi @dbarranco 

It fixes the issue after the ownership change.

Surprising no one reported this so far.
I think this issues exists for the past tags as well (last i tried was `bitnami/dokuwiki:2016`).

Regards,
Richard

**Comment by dbarranco** [comment] 2017-05-10 12:47
Hi @imRichardNg 

Glad it could solve the issue. I'm proceeding to close this issue.

Feel free to re-open it if you find any other issue related to permissions.

Best regards!

**Comment by fbjerggaard** [comment] 2017-08-29 12:33
It seems like this issue hasn't been fixed yet? I still get errors on the newest image (pulled the other day)

**Comment by carrodher** [comment] 2017-09-11 15:13
Hi,
latest releases have been automatically published when detecting a new version of DokuWiki, but no changes have been implemented in our logic.
If DokuWiki developers release a new version it is possible that our system publishes a new release, but this does not imply that the issue is solved.

We are going to work to solve the issue, we will notify you here when it is corrected.

Regards!

**Comment by carrodher** [comment] 2017-09-15 14:57
Hi @imRichardNg @fbjerggaard,

I just released a [new revision](https://github.com/bitnami/bitnami-docker-dokuwiki/releases/tag/0.20170219.201708232029-r1).
On this new revision, we solved the issue related to the wrong permissions installing plugins and templates also `lib/plugins` and `lib/tpl` are persisted by default.

I will close the issue if you find any other problem related to this topic do not hesitate to reopen it.

**Closed by carrodher** 2017-09-15 14:57 UTC
Labels: bug

**Comment by mohamed-okasha** [comment] 2018-10-17 10:53
I just deployed bitnami image in GCP but when i try install new template this message had showed to me:
Template directory is not writable

**Comment by mohamed-okasha** [comment] 2018-10-21 12:13
Google marketplace

**Comment by carrodher** [comment] 2018-10-22 07:54
Hi, we provide technical support in our [forum](https://community.bitnami.com/). Our team is actively monitoring it and will be glad to help you there, usually within a business day, and the whole community will benefit from your contribution. Could you please post your question by creating a new forum thread?

This GitHub service is only used to provide support for issues involving containers, kubernetes, Docker, etc.

**Comment by carrodher** [comment] 2018-10-22 07:56
Hi, we provide technical support in our [forum](https://community.bitnami.com/). Our team is actively monitoring it and will be glad to help you there, usually within a business day, and the whole community will benefit from your contribution. Could you please post your question by creating a new forum thread?

This GitHub service is only used to provide support involving Docker, Kubernetes, containers, etc issues.

**Comment by carrodher** [comment] 2018-10-22 07:57
Hi, we provide technical support in our [forum](https://community.bitnami.com/). Our team is actively monitoring it and will be glad to help you there, usually within a business day, and the whole community will benefit from your contribution. Could you please post your question by creating a new forum thread?

This GitHub service is only used to provide support involving Docker, Kubernetes, containers, etc issues.

**Comment by carrodher** [comment] 2018-10-22 07:58
Hi, we provide technical support in our [forum](https://community.bitnami.com/). Our team is actively monitoring it and will be glad to help you there, usually within a business day, and the whole community will benefit from your contribution. Could you please post your question by creating a new forum thread?

This GitHub service is only used to provide support involving Docker, Kubernetes, containers, etc issues.

**Comment by carrodher** [comment] 2018-10-22 08:05
Hi, we provide technical support in our [forum](https://community.bitnami.com/). Our team is actively monitoring it and will be glad to help you there, usually within a business day, and the whole community will benefit from your contribution. Could you please post your question by creating a new forum thread?

This help desk service is only used to provide support involving sensitive issues related to Kubernetes, Docker images, containers, etc.
