### ISSUE TITLE
error building from Dockerfile

### ISSUE THREAD

**Issue by viktor-c** [bitnami/bitnami-docker-dokuwiki#83] opened 2020-09-29 21:50 UTC
I have the issue described at [bitnami-minideb](https://github.com/bitnami/minideb/issues/89#issuecomment-701005140) I want to build the bitnami-docker-dokuwiki image using the Dockerfile. This fails.
I thought it is an error of `install_package` because the error kept appearing at this step of the image build. 

How to reproduce:
1. Clone dokuwiki repo
2. execute `docker build .`

it fails with `W: GPG error: http://deb.debian.org/debian buster InRelease: Couldn't execute /usr/bin/apt-key to check /var/lib/apt/lists/partial/deb.debian.org_debian_dists_buster_InRelease               
E: The repository 'http://deb.debian.org/debian buster InRelease' is not signed.`

I tried changing Dockerfile and noticed, that when i move `COPY prebuildfs /` further down, it does not fail anymore at the first step, but later on. So this leads me to believe, that there could be some kind of problem there.

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by viktor-c** [comment] 2020-09-29 21:56
Experimenting around: Deleting the directory `/usr` from `prebuildfs` solves the problem. This directory contains `sbin/install_packages`. I guess this is already included in minideb, because the build now works.

**Comment by juan131** [comment] 2020-09-30 07:23
Hi @viktor-c 

I just responded you in the PR you created. What specific steps are you following? I was able to build the image without issue following the ones below:

```console
$ git clone https://github.com/bitnami/bitnami-docker-dokuwiki.git
Cloning into 'bitnami-docker-dokuwiki'...
cd bitanremote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (48/48), done.
^Rceiving objects:   5% (420/8385)
remote: Total 8385 (delta 34), reused 60 (delta 20), pack-reused 8304
Receiving objects: 100% (8385/8385), 953.70 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (3689/3689), done.
juan:/tmp$ cd bitnami-docker-dokuwiki/20200729/debian-10/
juan:/tmp/bitnami-docker-dokuwiki/20200729/debian-10 (master)$ docker build . -t my-dokuwiki
[+] Building 51.4s (21/21) FINISHED
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                   0.0s
 => [internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 2.88kB                                                                                            0.0s
 => [internal] load metadata for docker.io/bitnami/minideb:buster                                                                 1.8s
 => [1/16] FROM docker.io/bitnami/minideb:buster@sha256:96583ce2ba23fe8bfb82cef8dc7d1cfec84c2a0e9b77700123527cbd74f1a557          3.4s
 => => resolve docker.io/bitnami/minideb:buster@sha256:96583ce2ba23fe8bfb82cef8dc7d1cfec84c2a0e9b77700123527cbd74f1a557           0.0s
 => => sha256:96583ce2ba23fe8bfb82cef8dc7d1cfec84c2a0e9b77700123527cbd74f1a557 528B / 528B                                        0.0s
 => => sha256:48efba5935f13833c73bf93cc35d41aa6912638338515ba9a9157f00cfcd8f26 910B / 910B                                        0.0s
 => => sha256:58212c1109c5214ba5c4c3ef9e785b56bae9223d58defae23919896e0ecac644 26.70MB / 26.70MB                                  2.4s
 => => extracting sha256:58212c1109c5214ba5c4c3ef9e785b56bae9223d58defae23919896e0ecac644                                         0.8s
 => [internal] load build context                                                                                                 0.0s
 => => transferring context: 127.55kB                                                                                             0.0s
 => [2/16] COPY prebuildfs /                                                                                                      0.1s
 => [3/16] RUN install_packages acl ca-certificates curl gzip libargon2-1 libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-  13.4s
 => [4/16] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "php" "7.3.22-4" --checksum 0117b9ea5dbd910acaf1e630c6  4.3s
 => [5/16] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "apache" "2.4.46-0" --checksum 93181ed22488a04139fe2a  10.2s
 => [6/16] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "libphp" "7.3.22-1" --checksum 18f03a612aa975b8d25822f  1.4s
 => [7/16] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "render-template" "1.0.0-1" --checksum a94f94357aa06f3  0.5s
 => [8/16] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.12.0-1" --checksum 51cfb1b7fd7b05b8abd1df027  0.6s
 => [9/16] RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "dokuwiki" "20200729.0.0-0" --checksum 97fb191e46aaa5e  1.4s
 => [10/16] RUN apt-get update && apt-get upgrade -y &&     rm -r /var/lib/apt/lists /var/cache/apt/archives                      3.3s
 => [11/16] RUN chmod g+rwX /opt/bitnami                                                                                          0.2s
 => [12/16] COPY rootfs /                                                                                                         0.0s
 => [13/16] RUN /opt/bitnami/scripts/php/postunpack.sh                                                                            0.3s
 => [14/16] RUN /opt/bitnami/scripts/apache/postunpack.sh                                                                         0.3s
 => [15/16] RUN /opt/bitnami/scripts/apache-modphp/postunpack.sh                                                                  0.3s
 => [16/16] RUN /opt/bitnami/scripts/dokuwiki/postunpack.sh                                                                       7.8s
 => exporting to image                                                                                                            1.8s
 => => exporting layers                                                                                                           1.8s
 => => writing image sha256:79009a5c1af9c95ad9fc220b2d1e9e6c006ed397e85ee06b3744739810823198                                      0.0s
 => => naming to docker.io/library/my-dokuwiki                                                                                    0.0s
```

**Comment by viktor-c** [comment] 2020-09-30 18:52
I can confirm that using you list of commands I can successfully build the image.
```
git clone https://github.com/bitnami/bitnami-docker-dokuwiki.git
cd bitnami-docker-dokuwiki/20200729/debian-10/
docker build . -t my-dokuwiki
```

However I was doing it differently: 
on the page https://github.com/bitnami/bitnami-docker-dokuwiki
click on the green button `Code` then download zip. Extract to a folder, cd into folder ...../debian-10
`docker build .` and error shows up. 

I tried again. Your method works, but mine not. 

Maybe permission related error?

**Comment by viktor-c** [comment] 2020-09-30 18:58
git clone method:
-rwxrwxr-x install_packages 
drwxrwxr-x prebuildfs, rootfs, sbin, opt, usr, bitnami, scripts

unzip method:
-rwxr-xr-x install_packages 
drwx------ prebuildfs, rootfs, sbin, opt, usr, bitnami, scripts

But all *.sh script files have identical permissions both methods.

**Comment by viktor-c** [comment] 2020-09-30 19:06
Other than that, why is install_packages included, when it is already provided by minideb?

**Comment by juan131** [comment] 2020-10-01 05:42
Hi @viktor-c 

Correct.. It seems the permissions are not correct when using the Zip method.

> Other than that, why is install_packages included, when it is already provided by minideb?

The reason is that the whole directory `20200729/debian-10/` is created by our pipeline based on metadata. Our metadata says that this images has as "build dependency" this `install_packages` and it includes the one for Debian automatically (it doesn't info about what comes with minideb already). 

This work like this by design, since our pipeline is designed to be able to rebuild the whole catalog regardless the base image (e.g. substituting MiniDeb with a Centos image that doesn't include `install_packages`)

**Comment by viktor-c** [comment] 2020-10-01 17:34
Hi @juan131 !

> Correct.. It seems the permissions are not correct when using the Zip method.
I will leave it to you to see if it is a problem with `github` or something else...

> This work like this by design, since our pipeline is designed to be able to rebuild the whole catalog regardless the base image (e.g. substituting MiniDeb with a Centos image that doesn't include install_packages)
Thanks for the background information.

I still got the image working for me. It was important to change the user id when building the image. Works flawless :)

@juan131 Thanks for the great job working on this container!

**Comment by juan131** [comment] 2020-10-02 07:46
Great! I am glad you could get it working :)

I proceed to close the issue, please do not hesitate to reopen it if you require further help.

**Closed by juan131** 2020-10-02 07:46 UTC
